export const page = String.raw`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="dark">
<meta name="theme-color" content="#09111d">
<title>Choose Your CloudStream Plugins | Adam Knight Personal Repository Builder</title>
<meta name="description" content="Personal Bundles is the independent companion to Adam Knight MegaRepo: select up to 100 CloudStream plugins and generate a shareable selected-only repo.json link.">
<meta name="robots" content="index, follow">
<link rel="canonical" href="https://adam-cloudstream-bundles.badass-insane.workers.dev/">
<link rel="icon" type="image/png" href="https://raw.githubusercontent.com/admknight/CloudstreamExtensions/refs/heads/master/assets/icon.png">
<link rel="apple-touch-icon" href="https://raw.githubusercontent.com/admknight/CloudstreamExtensions/refs/heads/master/assets/icon.png">
<meta property="og:title" content="Build a personal CloudStream repository | Adam Knight">
<meta property="og:description" content="Personal Bundles: choose your CloudStream plugins from Adam Knight MegaRepo and generate a selected-only repository URL. No account or hosted plugin binaries.">
<meta property="og:type" content="website">
<meta property="og:url" content="https://adam-cloudstream-bundles.badass-insane.workers.dev/">
<meta property="og:image" content="https://raw.githubusercontent.com/admknight/CloudstreamExtensions/refs/heads/master/assets/icon.png">
<meta name="twitter:card" content="summary">
<style>
:root{--bg:#09111d;--surface:#111e30;--surface2:#15263b;--line:#314561;--text:#f0f6ff;--muted:#adc0d6;--cyan:#70e0ff;--green:#7de7b2;--amber:#ffd18a}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;min-height:100vh;background:radial-gradient(circle at 25% -8%,#1a4060 0%,transparent 34rem),linear-gradient(#0b1524,#09111d 34rem);font:15px/1.5 system-ui,-apple-system,"Segoe UI",sans-serif;color:var(--text)}
a{color:var(--cyan)}button,input,select{font:inherit}button{cursor:pointer}button:disabled{cursor:not-allowed;opacity:.55}
.shell{width:min(1160px,calc(100% - 34px));margin:auto}nav{border-bottom:1px solid var(--line);background:#0c1929d9}nav .shell{display:flex;align-items:center;justify-content:space-between;gap:20px;min-height:72px;flex-wrap:wrap;padding:10px 0}.brand{display:inline-flex;align-items:center;gap:11px;min-width:0;font-weight:800;letter-spacing:-.015em;color:var(--text);text-decoration:none}.brand img{width:36px;height:36px;object-fit:contain;border-radius:9px;flex-shrink:0}.brand span{display:block;line-height:1.2}.brand small{display:block;color:var(--muted);font-weight:700;font-size:.72rem;letter-spacing:0;margin-top:3px}.links{display:flex;gap:20px;flex-wrap:wrap}.links a{font-size:.86rem;text-decoration:none;color:var(--muted)}.links a:hover{color:var(--text)}
.hero{padding:54px 0 26px}.eyebrow{color:var(--cyan);font-size:.73rem;text-transform:uppercase;font-weight:800;letter-spacing:.14em}h1{font-size:clamp(2.2rem,5.5vw,4.4rem);line-height:1.07;letter-spacing:-.055em;margin:12px 0 16px}.hero p{max-width:780px;font-size:1.06rem;color:var(--muted);margin:0}.notice{border:1px solid #385c69;background:#102934;padding:16px 18px;border-radius:13px;margin:19px 0 26px;color:#c8ecf1;font-size:.93rem}
h2{font-size:1.18rem;letter-spacing:-.025em;margin:0}.panel{background:linear-gradient(145deg,#13243a,#111c2c);border:1px solid var(--line);border-radius:17px;padding:21px;margin-bottom:22px}.panel p{margin:6px 0 0;color:var(--muted)}.filter-grid{display:grid;grid-template-columns:2fr 1fr 1fr;gap:12px;margin-top:18px}.field{display:flex;flex-direction:column;gap:7px;color:#dfebf9;font-size:.82rem;font-weight:700}.field input,.field select{min-width:0;width:100%;background:#0b1624;border:1px solid #40566f;color:var(--text);border-radius:9px;padding:11px 12px;outline-offset:2px}.field input:focus-visible,.field select:focus-visible{outline:2px solid var(--cyan)}.checks{display:flex;gap:19px;align-items:center;flex-wrap:wrap;margin-top:14px;color:#d5e6f8;font-size:.85rem}.checks label{display:flex;gap:8px;align-items:center}.checks input{accent-color:#49b6eb}
.toolbar{display:flex;align-items:center;justify-content:space-between;gap:15px;margin:23px 0 16px;flex-wrap:wrap}.hint{font-size:.82rem;color:var(--muted)}.actions{display:flex;gap:9px;flex-wrap:wrap}button,.button-link{background:#20334c;border:1px solid #506683;color:#eef6ff;font-weight:750;padding:10px 13px;border-radius:9px;text-decoration:none;display:inline-flex;align-items:center;justify-content:center;gap:7px}button:hover:not(:disabled),.button-link:hover{background:#2a425e}.primary{background:linear-gradient(135deg,#1574ae,#218cc0);border-color:#3bb0e4;color:white}.primary:hover:not(:disabled){background:#237fb5}
.cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px}.card{border-radius:14px;padding:17px;background:#112035;border:1px solid #2c4260;display:flex;flex-direction:column;gap:13px;min-width:0}.card.selected{border-color:#49aad5;background:#142d40}.card h3{margin:0;line-height:1.25;font-size:1.02rem;overflow-wrap:anywhere}.desc{margin:8px 0 0;color:var(--muted);font-size:.82rem;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden;min-height:40px}.tags{display:flex;gap:6px;flex-wrap:wrap}.tag{font-size:.7rem;background:#1d334d;border:1px solid #3d5471;border-radius:5px;padding:3px 6px}.tag.adult{color:#ffd4c0;border-color:#8c584d}.tag.warn{color:var(--amber)}.card button{margin-top:auto;align-self:flex-start;padding:8px 12px;font-size:.82rem}.card.selected button{border-color:#409fca}.empty{grid-column:1/-1;padding:30px;color:var(--muted);text-align:center;border:1px dashed #45607d;border-radius:14px}.pages{display:flex;align-items:center;justify-content:center;gap:15px;padding:26px 0 30px}.pages span{color:var(--muted);font-size:.86rem}
.bundle{margin-top:24px}.bundle strong{color:var(--green)}.bundle .help{font-size:.89rem;color:var(--muted);margin:6px 0 17px}.mode{border:1px solid #314d66;border-radius:12px;padding:15px;margin:12px 0;background:#0d1c2c}.mode h3{margin:0 0 4px;font-size:.99rem}.mode p{color:var(--muted);margin:0 0 10px;font-size:.84rem}.out{display:flex;gap:8px;align-items:center}.out input{min-width:0;flex:1;border-radius:8px;background:#081421;border:1px solid #40566e;color:#dceaff;padding:10px;font-size:.84rem}.out button{white-space:nowrap}.mode .buttons{margin-top:9px;display:flex;gap:9px;flex-wrap:wrap}.mode .buttons a{font-size:.83rem}.steps{padding-left:18px;margin:12px 0 0;color:#c7d9e9}.steps li{padding-bottom:6px}.status{min-height:25px;color:var(--cyan);font-size:.84rem;margin:12px 0}.error{color:#ffaeae}.small{color:var(--muted);font-size:.81rem}footer{margin:50px 0 22px;padding:25px 0;border-top:1px solid #304763;color:var(--muted);font-size:.8rem}.journey{list-style:none;padding:0;margin:24px 0 15px;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.journey li{background:#102239;border:1px solid #33506d;border-radius:13px;padding:17px;min-width:0}.journey strong{display:block;color:#f0f6ff;margin-bottom:7px;font-size:.94rem}.journey span{display:block;color:#b2c6dc;font-size:.85rem;line-height:1.5}.quick-links{display:flex;gap:8px 19px;flex-wrap:wrap;color:var(--muted);font-size:.88rem;margin:0 0 25px}.quick-links a{font-weight:750}.steps-title{font-size:1rem;margin:19px 0 8px;color:var(--green)}
@media(max-width:870px){.about-facts{grid-template-columns:1fr}.journey{grid-template-columns:1fr 1fr}.filter-grid{grid-template-columns:1fr 1fr}.filter-grid label:first-child{grid-column:1/-1}.cards{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:580px){.journey{grid-template-columns:1fr}.journey li{padding:14px}.hero{padding-top:34px}nav .shell{padding:16px 0;align-items:flex-start;flex-direction:column;gap:10px}.hero{padding-top:36px}.filter-grid,.cards{grid-template-columns:1fr}.filter-grid label:first-child{grid-column:auto}.panel{padding:16px}.out{flex-direction:column;align-items:stretch}.out input{width:100%}.toolbar{align-items:flex-start;flex-direction:column}.checks{align-items:flex-start;flex-direction:column;gap:8px}}
.about-project{margin-top:20px}.about-head h2{font-size:clamp(1.25rem,3vw,1.65rem);letter-spacing:-.03em}.about-head>p:last-child{line-height:1.65;max-width:830px}.about-head .eyebrow{color:var(--cyan);font-size:.7rem;font-weight:800;letter-spacing:.12em;margin-bottom:7px;text-transform:uppercase}.about-facts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:19px 0 17px}.about-facts>div{background:#0d1b2d;border:1px solid #304760;border-radius:11px;padding:15px}.about-facts strong{display:block;color:#edf7ff;margin-bottom:8px;font-size:.91rem}.about-facts span{color:#a9c0d5;font-size:.83rem;line-height:1.55;display:block}.about-source{font-size:.84rem;line-height:1.5}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}
</style>
</head>
<body>
<nav aria-label="Primary navigation"><div class="shell"><a class="brand" href="https://admknight.github.io/CloudstreamExtensions/" aria-label="Adam Knight MegaRepo home"><img src="https://raw.githubusercontent.com/admknight/CloudstreamExtensions/refs/heads/master/assets/icon.png" alt="" width="36" height="36"><span>Adam Knight Mega Repo<small>Personal Repository Builder</small></span></a><div class="links"><a href="https://admknight.github.io/CloudstreamExtensions/#install-full">Full MegaRepo</a><a href="https://admknight.github.io/CloudstreamExtensions/explore.html">Extension Explorer</a><a href="#about">About</a><a href="https://admknight.github.io/">Portfolio</a><a href="https://github.com/admknight/cloudstream-personal-bundles">GitHub</a></div></div></nav>
<main class="shell">
<header class="hero"><div class="eyebrow">Personal Repository Builder · Selected-only catalog</div><h1>Your CloudStream plugins.<br>Your selection.</h1><p>This tool creates a <strong>personal repository link</strong> listing only the extensions you select from Adam Knight MegaRepo. Add that link in CloudStream, then install the plugins you want. No account required.</p></header>
<ol class="journey" aria-label="Three steps to use a personal CloudStream repository">
  <li><strong>1 · Choose</strong><span>Search the published catalog and select up to 100 extensions.</span></li>
  <li><strong>2 · Generate</strong><span>Create and copy your personal HTTPS repo.json link. It contains your chosen plugins, not the full catalog.</span></li>
  <li><strong>3 · Add and install</strong><span>Paste the link into CloudStream Add Repository, then install extensions individually.</span></li>
</ol>
<div class="quick-links"><span><strong>You are building a separate plugin list, not installing plugins.</strong></span><span>Want everything? <a href="https://admknight.github.io/CloudstreamExtensions/#install-full">Get the full MegaRepo shortcode</a>.</span><span>Just looking? <a href="https://admknight.github.io/CloudstreamExtensions/explore.html">Browse in Extension Explorer</a>.</span></div>
<div class="notice"><strong>What this link does:</strong> It adds a repository containing only your selections. It does <strong>not</strong> install plugins automatically or edit the original MegaRepo. Install only extensions you trust; CloudStream plugins can run code. NSFW labels are based on upstream metadata, not a content guarantee.</div>
<section class="panel" aria-labelledby="choose-title"><h2 id="choose-title">1. Choose your extensions</h2><p>Search and filter the available upstream catalog. Entries marked down are excluded.</p>
<div class="filter-grid"><label class="field">Search plugins<input id="search" type="search" placeholder="Name, description or type" autocomplete="off"></label><label class="field">Language<select id="lang"><option value="">All languages</option></select></label><label class="field">Content type<select id="type"><option value="">All types</option></select></label></div>
<div class="checks"><label><input type="checkbox" id="adult"> Show NSFW-labeled extensions</label><label><input type="checkbox" id="only"> Show selected only</label></div></section>
<div class="toolbar"><div><strong id="summary">Loading current catalog...</strong><div class="hint"><span id="selection">0</span> selected · maximum 100 · selections are stored only in this browser</div></div><div class="actions"><button id="reset" type="button">Clear selection</button><button id="reload" type="button">Refresh catalog</button><button class="primary" id="build" type="button" disabled>Create my repository link</button></div></div>
<div id="message" class="status" role="status" aria-live="polite"></div>
<section class="cards" id="cards" aria-label="Available plugins"></section>
<div class="pages"><button type="button" id="prev" disabled>Previous</button><span id="page">Page 1</span><button type="button" id="next" disabled>Next</button></div>
<section class="panel bundle" id="bundle" hidden aria-labelledby="bundle-title"><h2 id="bundle-title">2. Generated selected-only repository URL</h2><p class="help">Copy a generated HTTPS <strong>repo.json</strong> URL below. It represents your selected extensions only. As upstream versions change, the same plugin identities remain linked to current MegaRepo metadata. To change your selection, generate a new URL and replace the old repository in CloudStream.</p><div id="modes"></div>
<h3 class="steps-title">3. Add the repository, then install the plugins</h3><ol class="steps"><li>On Android, tap <strong>Open in CloudStream</strong> if the app supports the link. Otherwise copy the HTTPS URL.</li><li>In CloudStream: <strong>Settings → Extensions → Add Repository</strong>, then paste the URL.</li><li>Install the plugins displayed in your custom repository. Adding a repository is not the same as installing plugins.</li></ol></section>
<p class="small">No account or server-side storage is used. The generated URL encodes the chosen plugin identifiers; anyone with the URL can view its selections. If an upstream plugin is removed, you will need to create a replacement bundle. This independent service must remain available for personalized URLs to work.</p>
<section id="about" class="panel about-project" aria-labelledby="about-title">
  <div class="about-head">
    <p class="eyebrow">About Personal Bundles</p>
    <h2 id="about-title">A MegaRepo companion, not a replacement.</h2>
    <p>Personal Bundles is a separate, read-only Cloudflare Worker built around Adam Knight MegaRepo's published extension catalog. It lets you create a personal repository list without modifying MegaRepo or hosting copies of plugin packages.</p>
  </div>
  <div class="about-facts">
    <div><strong>Choose what appears</strong><span>Select up to 100 extensions. Your generated link contains those plugin identities, not the entire catalog.</span></div>
    <div><strong>Keep current metadata</strong><span>Stable plugin identities follow published MegaRepo package versions after the cache refreshes. Changing your selection needs a new link.</span></div>
    <div><strong>Install inside CloudStream</strong><span>Add your selected-only repository URL in CloudStream, then install individual plugins. Adding a repository does not install anything automatically.</span></div>
  </div>
  <p class="about-source">Explore the <a href="https://admknight.github.io/CloudstreamExtensions/">full MegaRepo project</a>, read the <a href="https://github.com/admknight/cloudstream-personal-bundles">Personal Bundles source and documentation</a>, or browse in the <a href="https://admknight.github.io/CloudstreamExtensions/explore.html">Extension Explorer</a>.</p>
</section>
<footer>Personal repos list chosen extensions; they do not install anything automatically. No media or plugin binaries are hosted here. <a href="https://admknight.github.io/CloudstreamExtensions/#install-full">Full MegaRepo</a> · <a href="https://admknight.github.io/CloudstreamExtensions/explore.html">Explorer</a> · <a href="https://admknight.github.io/">Portfolio</a> · <a href="https://github.com/admknight/cloudstream-personal-bundles">Source code</a></footer>
</main>
<script>
(() => {
  'use strict';
  const LIMIT = 100, PAGE_SIZE = matchMedia('(max-width:580px)').matches ? 12 : 24;
  const STORE = 'adam-bundles-selected-keys-v1';
  const $ = id => document.getElementById(id);
  const ids = ['search','lang','type','adult','only','reset','reload','build','message','summary','selection','cards','page','prev','next','bundle','modes'];
  const ui = Object.fromEntries(ids.map(k => [k, $(k)]));
  let all = [], filtered = [], pageNum = 1;
  let selected = getStored(), failed = false;
  const str = x => typeof x === 'string' ? x.trim() : '';
  const types = item => (Array.isArray(item.tvTypes) ? item.tvTypes : []).flatMap(t => str(t).split(',')).map(x => x.trim()).filter(Boolean);
  function getStored() {try {const a=JSON.parse(localStorage.getItem(STORE)||'[]');return new Set(Array.isArray(a)?a.filter(x=>typeof x==='string'&&/^[a-f0-9]{16}$/.test(x)).slice(0,LIMIT):[]);}catch{return new Set();}}
  function save() {try{localStorage.setItem(STORE,JSON.stringify([...selected]));}catch{}}
  function el(tag,cls,value){const n=document.createElement(tag);if(cls)n.className=cls;if(value!==undefined)n.textContent=String(value);return n;}
  function note(text,isError=false){ui.message.textContent=text;ui.message.classList.toggle('error',isError);}
  function selectOptions(control,options,title){const old=control.value;control.replaceChildren(new Option(title,''));[...new Set(options)].filter(Boolean).sort((a,b)=>a.localeCompare(b)).forEach(x=>control.add(new Option(x,x)));if([...control.options].some(o=>o.value===old))control.value=old;}
  function addTags(box,p){const tags=el('div','tags');if(p.language)tags.append(el('span','tag',p.language.toUpperCase()));types(p).slice(0,4).forEach(t=>tags.append(el('span','tag',t)));tags.append(el('span','tag','v'+p.version));if(p.adult)tags.append(el('span','tag adult','NSFW label'));if(p.status!==1)tags.append(el('span','tag warn',p.status===2?'Slow':'Beta'));box.append(tags);}
  function card(p){const article=el('article','card'+(selected.has(p.id)?' selected':''));article.append(el('h3','',p.name),el('p','desc',p.description||'No description provided in the upstream catalog.'));addTags(article,p);const button=el('button','',selected.has(p.id)?'Remove':'Select');button.type='button';button.setAttribute('aria-pressed',String(selected.has(p.id)));button.setAttribute('aria-label',(selected.has(p.id)?'Remove ':'Select ')+p.name);button.addEventListener('click',()=>{if(selected.has(p.id))selected.delete(p.id);else{if(selected.size>=LIMIT){note('Maximum 100 selected. Remove one before adding another.',true);return;}selected.add(p.id);}save();refresh();});article.append(button);return article;}
  function render(){pageNum=Math.min(Math.max(1,pageNum),Math.max(1,Math.ceil(filtered.length/PAGE_SIZE)));const start=(pageNum-1)*PAGE_SIZE;const visible=filtered.slice(start,start+PAGE_SIZE);ui.cards.replaceChildren(...(visible.length?visible.map(card):[el('p','empty',failed?'Could not load the catalog. Use Refresh catalog to retry.':'No extensions match your current filters.') ]));ui.page.textContent='Page '+pageNum+' of '+Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));ui.prev.disabled=pageNum<=1;ui.next.disabled=start+PAGE_SIZE>=filtered.length;ui.summary.textContent=filtered.length+' matching / '+all.length+' available';ui.selection.textContent=String(selected.size);ui.build.disabled=selected.size===0||failed;ui.bundle.hidden=true;}
  function refresh(){const q=ui.search.value.trim().toLocaleLowerCase(),lng=ui.lang.value,tp=ui.type.value;filtered=all.filter(p=>{if(!ui.adult.checked&&p.adult)return false;if(ui.only.checked&&!selected.has(p.id))return false;if(lng&&p.language!==lng)return false;if(tp&&!types(p).includes(tp))return false;if(q&&![p.name,p.description,p.language,...types(p)].join(' ').toLocaleLowerCase().includes(q))return false;return true;}).sort((a,b)=>a.name.localeCompare(b.name,undefined,{sensitivity:'base'}));render();}
  function bundleToken(keys){const unique=[...new Set(keys)].sort();if(unique.length<1||unique.length>LIMIT)throw new Error('Invalid bundle size');const bytes=new Uint8Array(1+unique.length*8);bytes[0]=1;unique.forEach((key,i)=>{for(let j=0;j<8;j++)bytes[1+i*8+j]=parseInt(key.slice(j*2,j*2+2),16);});return btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
  async function copy(value){try{await navigator.clipboard.writeText(value);note('Repository URL copied. Paste it into CloudStream Add Repository.');}catch{note('Clipboard access unavailable. Select the URL text and copy manually.',true);}}
  function modeBox(token,mode,label,count,description){if(!count)return null;const url=location.origin+'/b/'+token+'/'+mode+'/repo.json';const group=el('section','mode');group.append(el('h3','',label+' · '+count+' extension'+(count===1?'':'s')),el('p','',description));const out=el('div','out'),field=el('input');field.value=url;field.readOnly=true;field.setAttribute('aria-label',label+' repository URL');field.addEventListener('focus',()=>field.select());field.addEventListener('click',()=>field.select());const btn=el('button','', 'Copy URL');btn.type='button';btn.addEventListener('click',()=>copy(url));out.append(field,btn);const buttons=el('div','buttons'),open=el('a','button-link','Open in CloudStream');open.href='cloudstreamrepo://'+location.host+'/b/'+token+'/'+mode+'/repo.json';open.rel='noopener noreferrer';buttons.append(open);group.append(out,buttons);return group;}
  function build(){if(!selected.size)return;const keys=[...selected].filter(k=>all.some(p=>p.id===k));if(keys.length!==selected.size){note('One or more saved plugins are no longer available. Refresh your selection.',true);return;}const chosen=all.filter(p=>selected.has(p.id));const adults=chosen.filter(p=>p.adult).length,normal=chosen.length-adults;const token=bundleToken(keys);ui.modes.replaceChildren(...[
    modeBox(token,'all','All my selected plugins',chosen.length,'All selected extensions, including any explicitly selected NSFW-labeled entries.'),
    modeBox(token,'sfw','SFW-labeled bundle',normal,'Only selected entries not labeled NSFW. Classification comes from upstream metadata.'),
    modeBox(token,'nsfw','NSFW-labeled bundle',adults,'Only selected entries labeled NSFW. Not an independent age or safety verification.')
  ].filter(Boolean));ui.bundle.hidden=false;ui.bundle.scrollIntoView({behavior:'smooth',block:'start'});note('Your personalized repository links are ready.');}
  async function load(){failed=false;ui.reload.disabled=true;note('Loading the current MegaRepo catalog...');try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);let response;try{response=await fetch('/api/catalog',{cache:'no-store',signal:controller.signal});}finally{clearTimeout(timer);}if(!response.ok)throw new Error('Catalog '+response.status);const data=await response.json();if(!Array.isArray(data.plugins)||!data.plugins.length)throw new Error('Invalid data');all=data.plugins.filter(p=>p&&typeof p.id==='string'&&/^[a-f0-9]{16}$/.test(p.id)&&typeof p.name==='string');const known=new Set(all.map(p=>p.id));selected=new Set([...selected].filter(k=>known.has(k)));save();selectOptions(ui.lang,all.map(p=>p.language).filter(Boolean),'All languages');selectOptions(ui.type,all.flatMap(types),'All types');pageNum=1;refresh();note('Choose your extensions, then select Create my repository link.');}catch{failed=true;all=[];filtered=[];render();note('Catalog unavailable. MegaRepo itself is unaffected; click Refresh catalog to retry.',true);}finally{ui.reload.disabled=false;}}
  [ui.search,ui.lang,ui.type,ui.adult,ui.only].forEach(input=>input.addEventListener(input===ui.search?'input':'change',()=>{pageNum=1;refresh();}));
  ui.reset.addEventListener('click',()=>{selected.clear();save();refresh();note('Selection cleared.');});ui.build.addEventListener('click',build);ui.reload.addEventListener('click',load);
  ui.prev.addEventListener('click',()=>{pageNum--;render();ui.cards.scrollIntoView({behavior:'smooth'});});ui.next.addEventListener('click',()=>{pageNum++;render();ui.cards.scrollIntoView({behavior:'smooth'});});
  load();
})();
</script>
</body>
</html>`;
